# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'SAPeerTwoPeer_In_Band_Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for SAPeerTwoPeer_In_Band_Demo
  pod 'SocketRocket'
  pod 'Masonry'
  pod 'IQKeyboardManager'
  pod 'QBImagePickerController'

end
